package agents

import (
	"context"
)

// ---------------------------------------------------------------------------
// Stop Hooks — post-query iteration processing
// Maps to TypeScript handleStopHooks in query/stopHooks.ts
// ---------------------------------------------------------------------------

// StopHookResult holds the outcome of running stop hooks.
type StopHookResult struct {
	// BlockingErrors are errors that prevent the query from continuing.
	BlockingErrors []string

	// PreventContinuation, when true, stops the query loop.
	PreventContinuation bool

	// AdditionalMessages are messages to inject into the history.
	AdditionalMessages []Message

	// HookMessages are messages generated by individual hooks.
	HookMessages []Message
}

// StopHook defines a single hook that runs after each query iteration.
type StopHook interface {
	// Name returns the hook identifier.
	Name() string

	// ShouldRun returns true if this hook should execute given the current state.
	ShouldRun(ctx context.Context, state *LoopState, stopReason string) bool

	// Run executes the hook and returns its result.
	Run(ctx context.Context, state *LoopState, stopReason string) *StopHookResult
}

// StopHookRegistry manages registered stop hooks.
type StopHookRegistry struct {
	hooks []StopHook
}

// NewStopHookRegistry creates a new empty registry.
func NewStopHookRegistry() *StopHookRegistry {
	return &StopHookRegistry{}
}

// Register adds a stop hook.
func (r *StopHookRegistry) Register(hook StopHook) {
	r.hooks = append(r.hooks, hook)
}

// HandleStopHooks runs all applicable stop hooks after a query iteration.
// Maps to TypeScript's handleStopHooks function.
//
// Hook categories (from stopHooks.ts):
//   - Stop hooks: run when the model stops (end_turn without tool_use)
//   - TeammateIdle hooks: run when a sub-agent signals idle
//   - TaskCompleted hooks: run when a task is marked complete
//
// Returns combined result of all hooks.
func (r *StopHookRegistry) HandleStopHooks(ctx context.Context, state *LoopState, stopReason string) *StopHookResult {
	combined := &StopHookResult{}

	for _, hook := range r.hooks {
		select {
		case <-ctx.Done():
			return combined
		default:
		}

		if !hook.ShouldRun(ctx, state, stopReason) {
			continue
		}

		result := hook.Run(ctx, state, stopReason)
		if result == nil {
			continue
		}

		combined.BlockingErrors = append(combined.BlockingErrors, result.BlockingErrors...)
		combined.AdditionalMessages = append(combined.AdditionalMessages, result.AdditionalMessages...)
		combined.HookMessages = append(combined.HookMessages, result.HookMessages...)

		if result.PreventContinuation {
			combined.PreventContinuation = true
		}
	}

	return combined
}

// ---------------------------------------------------------------------------
// Built-in stop hooks
// ---------------------------------------------------------------------------

// MaxTurnsHook stops execution when maximum turns are exceeded.
type MaxTurnsHook struct {
	MaxTurns int
}

func (h *MaxTurnsHook) Name() string { return "max_turns" }

func (h *MaxTurnsHook) ShouldRun(_ context.Context, state *LoopState, _ string) bool {
	return h.MaxTurns > 0 && state.TurnCount >= h.MaxTurns
}

func (h *MaxTurnsHook) Run(_ context.Context, _ *LoopState, _ string) *StopHookResult {
	return &StopHookResult{
		PreventContinuation: true,
		BlockingErrors:      []string{"Maximum turns exceeded"},
	}
}

// BudgetExhaustedHook stops execution when the token budget is depleted.
type BudgetExhaustedHook struct {
	Tracker *BudgetTracker
}

func (h *BudgetExhaustedHook) Name() string { return "budget_exhausted" }

func (h *BudgetExhaustedHook) ShouldRun(_ context.Context, _ *LoopState, _ string) bool {
	return h.Tracker != nil && h.Tracker.CheckBudget() == BudgetStop
}

func (h *BudgetExhaustedHook) Run(_ context.Context, _ *LoopState, _ string) *StopHookResult {
	return &StopHookResult{
		PreventContinuation: true,
		BlockingErrors:      []string{"Token budget exhausted"},
	}
}
