package agents

import (
	"context"
	"fmt"
	"time"
)

// ---------------------------------------------------------------------------
// Stop Hooks — post-query iteration processing
// Maps to TypeScript handleStopHooks in query/stopHooks.ts
// ---------------------------------------------------------------------------

// StopHookResult holds the outcome of running stop hooks.
type StopHookResult struct {
	// BlockingErrors are message-typed errors injected into the history.
	BlockingErrors []Message

	// BlockingErrorStrings are the raw error strings for summary/logging.
	BlockingErrorStrings []string

	// PreventContinuation, when true, stops the query loop.
	PreventContinuation bool

	// StopReason describes why continuation was prevented.
	StopReason string

	// AdditionalMessages are messages to inject into the history.
	AdditionalMessages []Message

	// HookMessages are messages generated by individual hooks.
	HookMessages []Message

	// HookCount is the number of hooks that executed.
	HookCount int

	// HookInfos tracks per-hook execution details.
	HookInfos []StopHookInfo

	// HasOutput indicates whether any hook produced visible output.
	HasOutput bool
}

// StopHookInfo tracks execution details of a single hook.
type StopHookInfo struct {
	Command    string `json:"command"`
	PromptText string `json:"prompt_text,omitempty"`
	DurationMs int64  `json:"duration_ms,omitempty"`
}

// StopHook defines a single hook that runs after each query iteration.
type StopHook interface {
	// Name returns the hook identifier.
	Name() string

	// ShouldRun returns true if this hook should execute given the current state.
	ShouldRun(ctx context.Context, state *LoopState, stopReason string) bool

	// Run executes the hook and returns its result.
	Run(ctx context.Context, state *LoopState, stopReason string) *StopHookResult
}

// StopHookRegistry manages registered stop hooks.
type StopHookRegistry struct {
	hooks []StopHook
}

// NewStopHookRegistry creates a new empty registry.
func NewStopHookRegistry() *StopHookRegistry {
	return &StopHookRegistry{}
}

// Register adds a stop hook.
func (r *StopHookRegistry) Register(hook StopHook) {
	r.hooks = append(r.hooks, hook)
}

// HandleStopHooks runs all applicable stop hooks after a query iteration.
// Maps to TypeScript's handleStopHooks function.
//
// Hook categories (from stopHooks.ts):
//   - Stop hooks: run when the model stops (end_turn without tool_use)
//   - TeammateIdle hooks: run when a sub-agent signals idle
//   - TaskCompleted hooks: run when a task is marked complete
//
// The ch parameter receives hook progress/system messages for streaming to the caller.
// Returns combined result of all hooks.
func (r *StopHookRegistry) HandleStopHooks(
	ctx context.Context,
	state *LoopState,
	stopReason string,
	toolCtx *ToolUseContext,
	stopHookActive bool,
	ch chan<- StreamEvent,
) *StopHookResult {
	hookStartTime := time.Now()
	combined := &StopHookResult{}

	// Guard against recursive stop hook execution
	if stopHookActive {
		return combined
	}

	for _, hook := range r.hooks {
		// Check for cancellation between hooks
		select {
		case <-ctx.Done():
			// Aborted during hook execution — emit interruption message
			interruptMsg := Message{
				Type:    MessageTypeSystem,
				Level:   "info",
				Content: []ContentBlock{{Type: ContentBlockText, Text: "[Request interrupted by user]"}},
			}
			if ch != nil {
				ch <- StreamEvent{Type: EventSystem, Message: &interruptMsg}
			}
			combined.PreventContinuation = true
			return combined
		default:
		}

		if !hook.ShouldRun(ctx, state, stopReason) {
			continue
		}

		combined.HookCount++

		result := hook.Run(ctx, state, stopReason)
		if result == nil {
			continue
		}

		// Merge results
		combined.BlockingErrors = append(combined.BlockingErrors, result.BlockingErrors...)
		combined.BlockingErrorStrings = append(combined.BlockingErrorStrings, result.BlockingErrorStrings...)
		combined.AdditionalMessages = append(combined.AdditionalMessages, result.AdditionalMessages...)
		combined.HookMessages = append(combined.HookMessages, result.HookMessages...)
		combined.HookInfos = append(combined.HookInfos, result.HookInfos...)

		if result.HasOutput {
			combined.HasOutput = true
		}

		if result.PreventContinuation {
			combined.PreventContinuation = true
			if result.StopReason != "" {
				combined.StopReason = result.StopReason
			}
			// Emit attachment for hook_stopped_continuation tracking
			attachMsg := Message{
				Type: MessageTypeAttachment,
				Attachment: &AttachmentData{
					Type:    "hook_stopped_continuation",
					Content: result.StopReason,
				},
			}
			if ch != nil {
				ch <- StreamEvent{Type: EventAttachment, Message: &attachMsg}
			}
		}
	}

	// Create summary system message if hooks ran
	if combined.HookCount > 0 && ch != nil {
		summaryMsg := createStopHookSummaryMessage(
			combined.HookCount,
			combined.BlockingErrorStrings,
			combined.PreventContinuation,
			combined.StopReason,
			combined.HasOutput,
		)
		ch <- StreamEvent{Type: EventSystem, Message: &summaryMsg}

		// Notify about errors
		if len(combined.BlockingErrorStrings) > 0 && toolCtx != nil && toolCtx.AddNotification != nil {
			toolCtx.AddNotification("Stop hook error occurred")
		}
	}

	_ = hookStartTime // available for duration logging

	if combined.PreventContinuation {
		return combined
	}

	if len(combined.BlockingErrors) > 0 {
		return combined
	}

	return combined
}

// createStopHookSummaryMessage builds a system message summarizing hook execution.
func createStopHookSummaryMessage(
	hookCount int,
	hookErrors []string,
	preventedContinuation bool,
	stopReason string,
	hasOutput bool,
) Message {
	var text string
	if preventedContinuation {
		text = fmt.Sprintf("[%d stop hook(s) ran — continuation prevented: %s]", hookCount, stopReason)
	} else if len(hookErrors) > 0 {
		text = fmt.Sprintf("[%d stop hook(s) ran — %d error(s)]", hookCount, len(hookErrors))
	} else if hasOutput {
		text = fmt.Sprintf("[%d stop hook(s) ran with output]", hookCount)
	} else {
		text = fmt.Sprintf("[%d stop hook(s) ran successfully]", hookCount)
	}

	return Message{
		Type:      MessageTypeSystem,
		Level:     "info",
		Timestamp: time.Now(),
		Content:   []ContentBlock{{Type: ContentBlockText, Text: text}},
	}
}

// ---------------------------------------------------------------------------
// Built-in stop hooks
// ---------------------------------------------------------------------------

// MaxTurnsHook stops execution when maximum turns are exceeded.
type MaxTurnsHook struct {
	MaxTurns int
}

func (h *MaxTurnsHook) Name() string { return "max_turns" }

func (h *MaxTurnsHook) ShouldRun(_ context.Context, state *LoopState, _ string) bool {
	return h.MaxTurns > 0 && state.TurnCount >= h.MaxTurns
}

func (h *MaxTurnsHook) Run(_ context.Context, state *LoopState, _ string) *StopHookResult {
	return &StopHookResult{
		PreventContinuation:  true,
		StopReason:           fmt.Sprintf("Reached maximum number of turns (%d)", h.MaxTurns),
		BlockingErrorStrings: []string{fmt.Sprintf("Maximum turns exceeded (%d)", h.MaxTurns)},
		AdditionalMessages: []Message{
			{
				Type: MessageTypeAttachment,
				Attachment: &AttachmentData{
					Type:      "max_turns_reached",
					MaxTurns:  h.MaxTurns,
					TurnCount: state.TurnCount,
				},
			},
		},
	}
}

// BudgetExhaustedHook stops execution when the token budget is depleted.
type BudgetExhaustedHook struct {
	Tracker *BudgetTracker
}

func (h *BudgetExhaustedHook) Name() string { return "budget_exhausted" }

func (h *BudgetExhaustedHook) ShouldRun(_ context.Context, _ *LoopState, _ string) bool {
	return h.Tracker != nil && h.Tracker.CheckBudget() == BudgetStop
}

func (h *BudgetExhaustedHook) Run(_ context.Context, _ *LoopState, _ string) *StopHookResult {
	return &StopHookResult{
		PreventContinuation:  true,
		StopReason:           "Token budget exhausted",
		BlockingErrorStrings: []string{"Token budget exhausted"},
	}
}

// ApiErrorSkipHook prevents stop hook execution when the last message was an API error.
// This avoids infinite loops where stop hooks trigger further API calls that also fail.
type ApiErrorSkipHook struct{}

func (h *ApiErrorSkipHook) Name() string { return "api_error_skip" }

func (h *ApiErrorSkipHook) ShouldRun(_ context.Context, state *LoopState, _ string) bool {
	// Check if the last assistant message was an API error
	for i := len(state.Messages) - 1; i >= 0; i-- {
		if state.Messages[i].Type == MessageTypeAssistant {
			return state.Messages[i].IsApiError
		}
	}
	return false
}

func (h *ApiErrorSkipHook) Run(_ context.Context, _ *LoopState, _ string) *StopHookResult {
	// When last message was API error, prevent continuation to avoid loops
	return &StopHookResult{
		PreventContinuation: true,
		StopReason:          "Skipping stop hooks due to API error",
	}
}

// ---------------------------------------------------------------------------
// TeammateIdleHook — runs when a sub-agent signals idle (multi-agent mode)
// Maps to TypeScript executeTeammateIdleHooks in utils/hooks.ts
// ---------------------------------------------------------------------------

// TeammateIdleHook checks if the current agent is a "teammate" and if so,
// runs the teammate idle hooks (e.g., notify the orchestrator).
type TeammateIdleHook struct {
	// IsTeammate returns true if the current agent is a teammate sub-agent.
	IsTeammate func() bool
	// GetAgentName returns the teammate's name.
	GetAgentName func() string
	// GetTeamName returns the team name.
	GetTeamName func() string
	// OnIdle is called when the teammate signals idle. It may return blocking
	// errors or prevent continuation.
	OnIdle func(ctx context.Context, agentName, teamName string) *StopHookResult
}

func (h *TeammateIdleHook) Name() string { return "teammate_idle" }

func (h *TeammateIdleHook) ShouldRun(_ context.Context, _ *LoopState, _ string) bool {
	return h.IsTeammate != nil && h.IsTeammate()
}

func (h *TeammateIdleHook) Run(ctx context.Context, _ *LoopState, _ string) *StopHookResult {
	if h.OnIdle == nil {
		return nil
	}
	agentName := ""
	if h.GetAgentName != nil {
		agentName = h.GetAgentName()
	}
	teamName := ""
	if h.GetTeamName != nil {
		teamName = h.GetTeamName()
	}
	result := h.OnIdle(ctx, agentName, teamName)
	if result != nil && result.PreventContinuation && result.StopReason == "" {
		result.StopReason = "TeammateIdle hook prevented continuation"
	}
	return result
}

// ---------------------------------------------------------------------------
// TaskCompletedHook — runs when a task is marked complete (multi-agent mode)
// Maps to TypeScript executeTaskCompletedHooks in utils/hooks.ts
// ---------------------------------------------------------------------------

// TaskCompletedHook checks for in-progress tasks owned by this teammate
// and runs task completion hooks for each.
type TaskCompletedHook struct {
	// IsTeammate returns true if the current agent is a teammate sub-agent.
	IsTeammate func() bool
	// ListInProgressTasks returns tasks currently in-progress for this agent.
	ListInProgressTasks func(ctx context.Context) []TaskInfo
	// OnTaskCompleted is called for each in-progress task. It may return
	// blocking errors or prevent continuation.
	OnTaskCompleted func(ctx context.Context, task TaskInfo) *StopHookResult
}

// TaskInfo holds minimal info about a tracked task.
type TaskInfo struct {
	ID          string `json:"id"`
	Subject     string `json:"subject"`
	Description string `json:"description"`
}

func (h *TaskCompletedHook) Name() string { return "task_completed" }

func (h *TaskCompletedHook) ShouldRun(_ context.Context, _ *LoopState, _ string) bool {
	return h.IsTeammate != nil && h.IsTeammate()
}

func (h *TaskCompletedHook) Run(ctx context.Context, _ *LoopState, _ string) *StopHookResult {
	if h.ListInProgressTasks == nil || h.OnTaskCompleted == nil {
		return nil
	}
	tasks := h.ListInProgressTasks(ctx)
	if len(tasks) == 0 {
		return nil
	}

	combined := &StopHookResult{}
	for _, task := range tasks {
		select {
		case <-ctx.Done():
			return combined
		default:
		}
		result := h.OnTaskCompleted(ctx, task)
		if result == nil {
			continue
		}
		combined.BlockingErrors = append(combined.BlockingErrors, result.BlockingErrors...)
		combined.BlockingErrorStrings = append(combined.BlockingErrorStrings, result.BlockingErrorStrings...)
		combined.HookMessages = append(combined.HookMessages, result.HookMessages...)
		if result.PreventContinuation {
			combined.PreventContinuation = true
			if result.StopReason != "" {
				combined.StopReason = result.StopReason
			} else {
				combined.StopReason = "TaskCompleted hook prevented continuation"
			}
		}
	}
	return combined
}

// ---------------------------------------------------------------------------
// CompactWarningHook — warns when context is near the limit
// Maps to TypeScript compactWarningHook in services/compact/compactWarningHook.ts
// ---------------------------------------------------------------------------

// CompactWarningHook emits a warning when token usage exceeds the warning threshold.
type CompactWarningHook struct {
	// ContextWindowTokens is the total context window size.
	ContextWindowTokens int
	// WarningThreshold is the ratio (0-1) at which to warn. Default: 0.85
	WarningThreshold float64
}

func (h *CompactWarningHook) Name() string { return "compact_warning" }

func (h *CompactWarningHook) ShouldRun(_ context.Context, state *LoopState, _ string) bool {
	if h.ContextWindowTokens <= 0 {
		h.ContextWindowTokens = 200000
	}
	if h.WarningThreshold <= 0 {
		h.WarningThreshold = 0.85
	}
	totalChars := 0
	for _, msg := range state.Messages {
		for _, block := range msg.Content {
			totalChars += len(block.Text) + len(block.Thinking) + len(string(block.Input))
		}
	}
	estimatedTokens := totalChars / 4
	ratio := float64(estimatedTokens) / float64(h.ContextWindowTokens)
	return ratio >= h.WarningThreshold
}

func (h *CompactWarningHook) Run(_ context.Context, _ *LoopState, _ string) *StopHookResult {
	return &StopHookResult{
		HookMessages: []Message{
			{
				Type:      MessageTypeSystem,
				Level:     "warning",
				Timestamp: time.Now(),
				Content: []ContentBlock{{
					Type: ContentBlockText,
					Text: "Context window is nearly full. Consider using /compact to reduce context size.",
				}},
			},
		},
		HasOutput: true,
		HookInfos: []StopHookInfo{
			{Command: "compact_warning", PromptText: "Context window warning"},
		},
	}
}

// ---------------------------------------------------------------------------
// ShellHookStopHook — runs user-defined shell hooks on Stop event
// Maps to TypeScript's executeStopHooks in utils/hooks.ts
// ---------------------------------------------------------------------------

// ShellHookStopHook wraps the ShellHookRegistry to run Stop-event shell hooks.
type ShellHookStopHook struct {
	// Registry is the shell hook registry containing user-configured hooks.
	Registry *ShellHookRegistry

	// SessionID is the current session ID for hook input.
	SessionID string

	// Cwd is the current working directory.
	Cwd string
}

func (h *ShellHookStopHook) Name() string { return "shell_hooks" }

func (h *ShellHookStopHook) ShouldRun(_ context.Context, _ *LoopState, _ string) bool {
	if h.Registry == nil {
		return false
	}
	return len(h.Registry.GetHooks(HookEventStop)) > 0
}

func (h *ShellHookStopHook) Run(ctx context.Context, state *LoopState, stopReason string) *StopHookResult {
	if h.Registry == nil {
		return nil
	}

	input := HookInput{
		SessionID:  h.SessionID,
		Cwd:        h.Cwd,
		StopReason: stopReason,
	}

	aggResult, err := RunHooksForEvent(ctx, h.Registry, HookEventStop, input, "")
	if err != nil {
		return &StopHookResult{
			BlockingErrorStrings: []string{fmt.Sprintf("shell hook error: %v", err)},
		}
	}

	result := &StopHookResult{}

	// Map blocking errors
	for _, be := range aggResult.BlockingErrors {
		result.BlockingErrorStrings = append(result.BlockingErrorStrings, be.BlockingError)
		result.BlockingErrors = append(result.BlockingErrors, Message{
			Type: MessageTypeAttachment,
			Attachment: &AttachmentData{
				Type:    "hook_blocking_error",
				Content: be.BlockingError,
			},
		})
	}

	if aggResult.PreventContinuation {
		result.PreventContinuation = true
		result.StopReason = aggResult.StopReason
	}

	// Map additional contexts as hook messages
	for _, ctx := range aggResult.AdditionalContexts {
		result.HookMessages = append(result.HookMessages, Message{
			Type:      MessageTypeSystem,
			Level:     "info",
			Timestamp: time.Now(),
			Content:   []ContentBlock{{Type: ContentBlockText, Text: ctx}},
		})
		result.HasOutput = true
	}

	return result
}

// ---------------------------------------------------------------------------
// BackgroundTaskStopHook — fires background tasks at end of turn
// Maps to TypeScript's post-turn background tasks in stopHooks.ts:
//   - executePromptSuggestion
//   - memory extraction
//   - auto-dream
// ---------------------------------------------------------------------------

// BackgroundTaskStopHook triggers background tasks after each completed turn.
// It always returns nil (no blocking) — tasks run asynchronously.
type BackgroundTaskStopHook struct {
	// Manager is the background task manager.
	Manager *BackgroundTaskManager

	// SessionID for task context.
	SessionID string

	// Cwd is the current working directory.
	Cwd string

	// IsBareMode skips background tasks in scripted/bare mode.
	IsBareMode bool
}

func (h *BackgroundTaskStopHook) Name() string { return "background_tasks" }

func (h *BackgroundTaskStopHook) ShouldRun(_ context.Context, _ *LoopState, stopReason string) bool {
	if h.Manager == nil || h.IsBareMode {
		return false
	}
	// Only run on end_turn (not on tool_use iterations)
	return stopReason == "end_turn"
}

func (h *BackgroundTaskStopHook) Run(_ context.Context, state *LoopState, stopReason string) *StopHookResult {
	if h.Manager == nil {
		return nil
	}

	taskCtx := BackgroundTaskContext{
		SessionID:  h.SessionID,
		Messages:   state.Messages,
		StopReason: stopReason,
		TurnCount:  state.TurnCount,
		Cwd:        h.Cwd,
	}

	// Fire-and-forget: tasks run in background goroutines
	h.Manager.RunEndOfTurnTasks(taskCtx)

	return nil
}
